package mining

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// SaverConfig contains configuration for saving mining results
type SaverConfig struct {
	ConfigDir    string // Base config directory (e.g., ~/.config/neonflare)
	Repository   string // Repository name (e.g., "owner/repo")
	AgentName    string // Name of agent used for mining
	UpdateMode   bool   // Whether this is an update to existing rules
	ExistingPath string // Path to existing rules file (for updates)
}

// SaveMiningResult saves the mining result to a file
func SaveMiningResult(result *MiningResult, config SaverConfig) (string, error) {
	// Determine config directory
	configDir := config.ConfigDir
	if configDir == "" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}
		configDir = filepath.Join(homeDir, ".config", "neonflare")
	}

	// Create rules directory
	rulesDir := filepath.Join(configDir, "reviewer-prompts", "rules")
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create rules directory: %w", err)
	}

	// Generate filename
	var filename string
	if config.UpdateMode && config.ExistingPath != "" {
		// Update mode: use existing filename
		filename = filepath.Base(config.ExistingPath)
	} else {
		// New file mode: generate filename from repo and date
		repoName := sanitizeRepoName(config.Repository)
		timestamp := time.Now().Format("2006-01-02")
		filename = fmt.Sprintf("team-rules-%s-%s.md", repoName, timestamp)
	}

	// Full path
	outputPath := filepath.Join(rulesDir, filename)

	// Add metadata header to content
	var fileContent strings.Builder

	// Only add metadata if not already present (agent might have formatted it)
	if !strings.HasPrefix(result.Content, "# ") && !strings.HasPrefix(result.Content, "---") {
		fileContent.WriteString(fmt.Sprintf("# Mined Review Rules\n\n"))
		fileContent.WriteString(fmt.Sprintf("**Repository:** %s\n", config.Repository))
		fileContent.WriteString(fmt.Sprintf("**Generated by:** %s\n", config.AgentName))
		fileContent.WriteString(fmt.Sprintf("**Date:** %s\n", time.Now().Format(time.RFC3339)))
		fileContent.WriteString(fmt.Sprintf("**PRs Analyzed:** %d\n", result.PRCount))
		fileContent.WriteString(fmt.Sprintf("\n---\n\n"))
	}

	fileContent.WriteString(result.Content)

	// Write to file
	if err := os.WriteFile(outputPath, []byte(fileContent.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write rules file: %w", err)
	}

	return outputPath, nil
}

// sanitizeRepoName converts "owner/repo" to "owner-repo"
func sanitizeRepoName(repo string) string {
	// Replace slashes with dashes
	sanitized := strings.ReplaceAll(repo, "/", "-")
	// Remove any other special characters
	sanitized = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			return r
		}
		return '-'
	}, sanitized)
	// Convert to lowercase
	return strings.ToLower(sanitized)
}

// FindExistingRules looks for existing rules files for a repository
func FindExistingRules(configDir string, repository string) ([]string, error) {
	if configDir == "" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("failed to get home directory: %w", err)
		}
		configDir = filepath.Join(homeDir, ".config", "neonflare")
	}

	rulesDir := filepath.Join(configDir, "reviewer-prompts", "rules")

	// Check if directory exists
	if _, err := os.Stat(rulesDir); os.IsNotExist(err) {
		return []string{}, nil
	}

	// List all markdown files
	entries, err := os.ReadDir(rulesDir)
	if err != nil {
		return nil, fmt.Errorf("failed to read rules directory: %w", err)
	}

	repoName := sanitizeRepoName(repository)
	pattern := fmt.Sprintf("team-rules-%s-", repoName)

	var matchingFiles []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if strings.HasPrefix(entry.Name(), pattern) && strings.HasSuffix(entry.Name(), ".md") {
			fullPath := filepath.Join(rulesDir, entry.Name())
			matchingFiles = append(matchingFiles, fullPath)
		}
	}

	return matchingFiles, nil
}

// LoadRulesFile reads an existing rules file
func LoadRulesFile(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read rules file: %w", err)
	}
	return string(content), nil
}
