// Generated by Wrangler on Sun Apr 07 2024 00:24:48 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "production_value";
	SESSION_SECRET: string;
	DB: D1Database;
}
